In [1]:
20000 + 1500

21500

In [2]:
20000 - 1500

18500

In [3]:
20000 * 1500

30000000

In [4]:
20000 / 1500

13.333333333333334

In [5]:
import numpy as np

In [6]:
A = np.array([1,2,3])
B = np.array([4,5,6])
A2 = np.array([[1,2],[3,4]])
B2 = np.array([[5,6],[7,8]])

In [7]:
# Both A and B are 1D Array
print(np.dot(A,B))
print(np.vdot(A,B))

32
32


In [8]:
# Both A2 and B2 are 2D Array
print(np.dot(A2,B2))

# Preferred Functions for 2D Dot Product:
print(np.matmul(A2,B2))
print(A2 @ B2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
# Either A or B is scaler
print(np.dot(A,2))

# Preferred Function:
print(np.multiply(A,2))
print(A*2)

[2 4 6]
[2 4 6]
[2 4 6]


In [10]:
# Vector Multiplication / Cross Product
print(np.cross(A,B))
print(np.cross(A2,B2))

[-3  6 -3]
[-4 -4]


In [11]:
# Matrix
Mat1 = np.matrix('1 2 3; 4 5 6')
Mat2 = np.matrix('7 8 9; 10 11 12')
Mat3 = np.matrix('7 8; 9 10; 11 12')

In [14]:
# Dimensions
print(np.shape(Mat1))
print(np.shape(Mat2))
print(np.shape(Mat3))

(2, 3)
(2, 3)
(3, 2)


In [15]:
np.matmul(Mat1,Mat2)

ValueError: ignored

In [16]:
np.matmul(Mat1,Mat3)

matrix([[ 58,  64],
        [139, 154]])

In [17]:
# T
np.transpose(Mat3)

matrix([[ 7,  9, 11],
        [ 8, 10, 12]])

In [18]:
Mat3.T

matrix([[ 7,  9, 11],
        [ 8, 10, 12]])

In [19]:
Mat3.getT()

matrix([[ 7,  9, 11],
        [ 8, 10, 12]])

In [26]:
# Determinant
Mat4 = np.matrix('1 2 3; 6 5 4; 8 7 9')
np.linalg.det(Mat4)

-20.99999999999999

In [27]:
# Inverse
x = np.array([[1,2],[3,4]])
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
#Sys of Eq
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

In [32]:
# Eigen val
X = np.diag((1,2,3))
Ev, V = np.linalg.eig(X)
print(Ev)
print(V)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
X = np.diag((1,2,3))
np.linalg.eigvals(X)

array([1., 2., 3.])