In [103]:
pip install numpy # Install

In [104]:
import numpy as np # Import

In [105]:
print(np.__version__) # Get Version
print(np.show_config()) # Get Config - Libraries, directory and language in system on which NumPy was built.

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [106]:
print(np.info(np.add)) # Similar to classic help() command

None


In [107]:
# 1D Array
print(np.array([1,2,3]))

# 2D Array
print(np.array([(1,2,3),(4,5,6)]))

# Series/Range Array
np.arange(1,20,2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [108]:
print(np.linspace(0,2,9)) # Gives 9 equally spaced values between 0 and 2

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [109]:
# Array of Zeros
print(np.zeros((1,2)))
# Array of Ones
print(np.ones((1,2)))

[[0. 0.]]
[[1. 1.]]


In [110]:
# Random Array
print(np.random.random((5,5))) # Return random float from 0 to 1. Can also use Randint or other functions instead.

# Empty Array
print(np.empty((2,2))) # Outputs arbitary uninitialized data

[[0.06514682 0.96725276 0.32319201 0.93013219 0.54126933]
 [0.49171604 0.74464638 0.01366618 0.35076422 0.41683827]
 [0.36924322 0.75896178 0.51948641 0.32198268 0.10155189]
 [0.10868055 0.28844802 0.46168197 0.03902628 0.54905865]
 [0.42871473 0.51348613 0.55416459 0.20151332 0.45782815]]
[[1.         1.        ]
 [0.33333333 0.25      ]]


In [111]:
xyz_array = np.array([(1,2,3),(4,5,6)])
xyz_array.shape # Get dimensions of any array

(2, 3)

In [112]:
len(xyz_array) # Length of an Array

2

In [113]:
xyz_array.ndim # Number of Dimensions --> This case 2D

2

In [114]:
xyz_array.dtype # Data type of array

dtype('int64')

In [115]:
# To convert a data type
xyz_array.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [116]:
type(xyz_array) # Numpy Array = numpy.ndarray

numpy.ndarray

In [117]:
copy_array = np.copy(xyz_array) # Will Return a np.array always
print(copy_array)
copy_array_hard = xyz_array.copy() # Will Return whatever type xyz_array is
print(copy_array_hard)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [118]:
rand_array = np.random.randint(0,10,(3,3)) # randint(low,high,size,dtype)
print(rand_array)
print("Sorted R:")
print(np.sort(rand_array)) # Sorts Each Row and not complete array/matrix
print("Sorted C:")
print(np.sort(rand_array,axis=0)) # Sort for Column
print("Sorted M:")
print(np.sort(rand_array,axis=1,kind='quicksort')) # Sort with default quicksort. Can use other sorting methods.

[[6 6 2]
 [2 4 0]
 [5 2 4]]
Sorted R:
[[2 6 6]
 [0 2 4]
 [2 4 5]]
Sorted C:
[[2 2 0]
 [5 4 2]
 [6 6 4]]
Sorted M:
[[2 6 6]
 [0 2 4]
 [2 4 5]]


In [119]:
np.append(xyz_array,copy_array) # Array is flattened if axis not given

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [120]:
np.append(xyz_array,copy_array,axis=0) # Joined column wise - values must have correct shape

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [121]:
np.insert(xyz_array,2,[7,8,9],axis=0) # Inserts values at index 2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.resize(xyz_array,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
np.resize(xyz_array,(5,3)) # Can recycle elements

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [124]:
# Row Delete
print(np.delete(xyz_array,1,axis=0))

# Column Delete
print(np.delete(xyz_array,[2],axis=1))

[[1 2 3]]
[[1 2]
 [4 5]]


In [125]:
np.concatenate((xyz_array,copy_array),axis=0) # np.append() uses np.concatenate()

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [126]:
np.concatenate((xyz_array,copy_array),axis=1) # concatenate is faster

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [127]:
np.vstack((xyz_array,copy_array)) # Vertical Stack

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [128]:
np.hstack((xyz_array,copy_array)) # Horizontal Stack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [129]:
np.split(xyz_array,2) # Divite array equally

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [130]:
np.array_split(xyz_array,4) # Might not divide array equally

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [131]:
np.hsplit(xyz_array, 3) # Splits horizontally

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

In [132]:
xyz_array.flatten() # C-Row F-Column A-Column is array is Fortran otherwise row K-In order of memory allocation

array([1, 2, 3, 4, 5, 6])

In [133]:
np.transpose(xyz_array)
# or
xyz_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [134]:
np.linalg.inv(np.array([[2,3],[2,2]])) # linear algebra - inverse / LinAlgError if inversion fails

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [135]:
np.add(xyz_array,10)

array([[11, 12, 13],
       [14, 15, 16]])

In [136]:
np.subtract(xyz_array, 11)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5]])

In [137]:
np.divide(xyz_array, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [138]:
np.multiply(xyz_array, 3)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [139]:
np.sqrt(xyz_array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [140]:
# np.sin(), np.cos(), np.log(), np.dot(x,y) - few more examples
np.roots([-12,-7,11,7,1])

array([ 1.        , -1.        , -0.33333333, -0.25      ])

In [141]:
np.mean(xyz_array)

3.5

In [142]:
np.median(xyz_array)

3.5

In [143]:
np.std(xyz_array)

1.707825127659933

In [144]:
xyz_array.sum()

21

In [145]:
xyz_array.min()

1

In [146]:
xyz_array.max()

6

In [147]:
xyz_array.max(axis=1)

array([3, 6])

In [148]:
xyz_array.cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [149]:
xyz_array.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])